coverage:
  status:
    project:
      default:
        target: 60%
    patch:
      default:
        target: 60%
flags:
  node:
    carryforward: true
  rust:
    carryforward: true
  storybook:
    carryforward: true
