export { DummyScreen } from './src/DummyScreen';
export { ChatItem } from './src/ChatItem';
export { ChatView } from './src/ChatView';
export { BottomNavigation } from './src/BottomNavigation';
export type { BottomNavigationProps } from './src/BottomNavigation';
export { TopBar } from './src/TopBar';
export type { TopBarProps } from './src/TopBar';
export { ChatsScreen } from './src/ChatsScreen';
export type { ChatsScreenProps, Chat } from './src/ChatsScreen';
export { mockChats } from './src/ChatsScreen';
export { SettingsScreen } from './src/SettingsScreen';
export type { SettingsScreenProps } from './src/SettingsScreen';
