/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function debugPrint(msg: string): void;
export declare function debugTcpConnect(host: string, port: number): boolean;
export declare function debugHttpGet(url: string): Promise<string>;
export interface Void {}
export declare function createClient(
  hsUrl: string,
  storePath: string,
): Promise<bigint>;
export declare function clientLogin(
  handle: bigint,
  username: string,
  password: string,
): Promise<Void>;
export declare function clientLogout(handle: bigint): Promise<Void>;
export declare function clientIsAuthenticated(handle: bigint): Promise<boolean>;
export declare function clientFree(handle: bigint): void;
export declare function clientGetRooms(handle: bigint): string;
export declare function clientSendText(
  handle: bigint,
  roomId: string,
  body: string,
): void;
export declare function clientStartSyncLoop(
  handle: bigint,
  timeoutMs: bigint,
): void;
export declare function clientStopSyncLoop(handle: bigint): void;
export declare function clientSyncOnce(handle: bigint, timeoutMs: bigint): void;
export declare function clientSendReaction(
  handle: bigint,
  roomId: string,
  eventId: string,
  key: string,
): void;
export declare function clientRedact(
  handle: bigint,
  roomId: string,
  eventId: string,
  reason?: string | undefined | null,
): void;
export declare function clientSendReadReceipt(
  handle: bigint,
  roomId: string,
  eventId: string,
): void;
export declare function clientSetTyping(
  handle: bigint,
  roomId: string,
  isTyping: boolean,
  timeoutMs: number,
): void;
export declare function clientSearchUsers(
  handle: bigint,
  query: string,
  limit: number,
): string;
export declare function clientGetDevices(handle: bigint): string;
export declare function clientRenameDevice(
  handle: bigint,
  deviceId: string,
  name: string,
): void;
export declare function clientDeleteDevice(
  handle: bigint,
  deviceId: string,
): void;
export declare function clientSetPresence(
  handle: bigint,
  stateCode: number,
): void;
export declare function clientGetPresence(
  handle: bigint,
  userId: string,
): number;
export declare function clientCreateRoom(
  handle: bigint,
  name: string | undefined | null,
  topic: string | undefined | null,
  isPublic: boolean,
): string;
export declare function clientJoinRoom(
  handle: bigint,
  idOrAlias: string,
): string;
export declare function clientLeaveRoom(handle: bigint, roomId: string): void;
export declare function clientUploadMedia(
  handle: bigint,
  base64Data: string,
  mime: string,
): string;
export declare function clientDownloadMedia(
  handle: bigint,
  uri: string,
): string;
